import { useEffect, useRef } from "react";
import mermaid from "mermaid";
import { colors } from "../utils/colors";

export const MermaidView = ({ chart, title }) => {
  const containerRef = useRef(null);

  useEffect(() => {
    mermaid.initialize({ startOnLoad: false, theme: "dark", suppressErrorRendering: true });
    if (chart && containerRef.current) {
      const id = `mermaid-svg-${Math.random().toString(36).substr(2, 9)}`;
      mermaid.render(id, chart).then((res) => {
        if (containerRef.current) {
          containerRef.current.innerHTML = res.svg;
        }
      }).catch(err => {
        if (containerRef.current) {
          containerRef.current.innerHTML = `<div style="color: red; text-align: center;">Failed to render mind map.<br>${err.message}</div>`;
        }
        // Mermaid sometimes injects error SVGs globally into the DOM when rendering fails.
        const errorElement = document.getElementById("d" + id);
        if (errorElement) errorElement.remove();
      });
    }
  }, [chart]);

  return (
    <div style={{ background: colors.surface, borderRadius: 16, padding: 24, border: `1px solid ${colors.border}` }} className="printable-content">
      <div className="print-only" style={{ display: "none", marginBottom: 20, borderBottom: "2px solid #000", paddingBottom: 10 }}>
        <h1 style={{ margin: 0, fontSize: 24 }}>{title} - Mind Map</h1>
        <div style={{ fontSize: 12, color: "#666", marginTop: 5 }}>Generated by MindScribe AI on {new Date().toLocaleDateString()}</div>
      </div>
      <div style={{ color: colors.textMuted, fontSize: 12, marginBottom: 16, fontWeight: 500 }} className="no-print">TOPIC MIND MAP</div>
      <div style={{ overflow: "auto", minHeight: 400, textAlign: "center", display: "block" }} ref={containerRef} />
    </div>
  );
};
